<?php

namespace Database\Seeders;

use App\Models\PaketKuesioner;
use App\Models\PaketQuesionerDetail;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class PaketKuesionerDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'tes123',
            'pertanyaan' => 'Apakah kamu suka?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 1,
            'is_required' => 1,
            'options' => json_encode(["ya", "tidak"]),
            'index' => 1,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'tes1234',
            'pertanyaan' => 'Apakah kamu bisa?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 1,
            'is_required' => 1,
            'options' => json_encode(["ya", "tidak"]),
            'index' => 2,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'tes1235',
            'pertanyaan' => 'Apakah kamu kuat?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 1,
            'is_required' => 1,
            'options' => json_encode(["ya", "tidak"]),
            'index' => 3,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'tes123545',
            'pertanyaan' => 'pilih yang kamu suka?',
            'tipe_id' => 12,
            'id_paket_quesioners' => 1,
            'is_required' => 1,
            'options' => json_encode(["fasih", "ahnaf", "marzuki"]),
            'index' => 4,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'tes1235',
            'pertanyaan' => 'Apakah kamu kuat?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 1,
            'is_required' => 1,
            'options' => json_encode(["ya", "tidak"]),
            'index' => 5,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'tes1236',
            'pertanyaan' => 'Berikan alasan anda?',
            'tipe_id' => 1,
            'id_paket_quesioners' => 1,
            'is_required' => 1,
            'index' => 6,
        ]);



        // Tracer Study
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'kdptimsmh',
            'pertanyaan' => 'Kode Perguruan Tinggi',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode(["005019"]),
            'index' => 1,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'kdpstmsmh',
            'pertanyaan' => 'Kode Program Studi',
            'tipe_id' => 10,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 2,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'nimhsmsmh',
            'pertanyaan' => 'NIM',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 3,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'nmmhsmsmh',
            'pertanyaan' => 'Nama Lengkap',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 4,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'telpomsmh',
            'pertanyaan' => 'Nomor Telepon/HP (Whatsapp)',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 5,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'emailmsmh',
            'pertanyaan' => 'Alamat Email',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 6,
        ]);

        $now = Carbon::now();
        $yearsArray = [];
        for ($i = 0; $i < 6; $i++) {
            $year = $now->subYears(1)->year;
            $yearsArray[] = $year;
        }

        $now = Carbon::now();
        $yearsArray = array_reverse($yearsArray);


        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'tahun_lulus',
            'pertanyaan' => 'Tahun Lulus',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode($yearsArray),
            'index' => 7,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'nik',
            'pertanyaan' => 'NIK (Nomor Induk Kependudukan/No KTP)',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 8,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'npwp',
            'pertanyaan' => 'NPWP (Nomor Pokok Wajib Pajak)',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 9,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f8',
            'pertanyaan' => 'Jelaskan status Anda saat ini?',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Bekerja (full time/part time)",
                "2 - Belum Memungkinakn Bekerja",
                "3 - Wiraswasta",
                "4 - Melanjutkan Pendidikan",
                "5 - Tidak kerja tetapi sedang mencari kerja",
            ]),
            'index' => 10,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f504',
            'pertanyaan' => 'Apakah Anda telah mendapatkan pekerjaan <= 6 bulan / termasuk bekerja sebelum lulus?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - ya",
                "2 - tidak"
            ]),
            'index' => 11,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f502',
            'pertanyaan' => 'Berapa bulan anda mendapatkan pekerjaan SEBELUM LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'index' => 12,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f505',
            'pertanyaan' => 'Berapa rata-rata pendapatan Anda per bulan ?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                'Rp. 1.000.000',
                'Rp. 1.500.000',
                'Rp. 2.000.000',
                'Rp. 2.500.000',
                'Rp. 3.000.000',
                'Rp. 3.500.000',
                'Rp. 4.000.000',
                'Rp. 4.500.000',
                'Rp. 5.000.000',
                'Rp. 6.000.000',
                '>Rp. 8.000.000',
            ]),
            'index' => 13,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f506',
            'pertanyaan' => 'Berapa bulan Anda MENDAPATKAN PEKERJAAN SETELAH LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'index' => 14,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f5a1',
            'pertanyaan' => 'Dimana lokasi provinsi tempat Anda bekerja??',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "010000 - Prov. D.K.I. Jakarta",
                "020000 - Prov. Jawa Barat",
                "030000 - Prov. Jawa Tengah",
                "040000 - Prov. D.I. Yogyakarta",
                "050000 - Prov. Jawa Timur",
                "060000 - Prov. Aceh",
                "070000 - Prov. Sumatera Utara",
                "080000 - Prov. Sumatera Barat",
                "090000 - Prov. Riau",
                "100000 - Prov. Jambi",
                "110000 - Prov. Sumatera Selatan",
                "120000 - Prov. Lampung",
                "130000 - Prov. Kalimantan Barat",
                "140000 - Prov. Kalimantan Tengah",
                "150000 - Prov. Kalimantan Selatan",
                "160000 - Prov. Kalimantan Timur",
                "170000 - Prov. Sulawesi Utara",
                "180000 - Prov. Sulawesi Tengah",
                "190000 - Prov. Sulawesi Selatan",
                "200000 - Prov. Sulawesi Tenggara",
                "210000 - Prov. Maluku",
                "220000 - Prov. Bali",
                "230000 - Prov. Nusa Tenggara Barat",
                "240000 - Prov. Nusa Tenggara Timur",
                "250000 - Prov. Papua",
                "260000 - Prov. Bengkulu",
                "270000 - Prov. Maluku Utara",
                "280000 - Prov. Banten",
                "290000 - Prov. Bangka Belitung",
                "300000 - Prov. Gorontalo",
                "310000 - Prov. Kepulauan Riau",
                "320000 - Prov. Papua Barat",
                "330000 - Prov. Sulawesi Barat",
                "340000 - Prov. Kalimantan Utara",
                "999999 - Luar Negeri"
            ]),
            'index' => 15,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f5a2',
            'pertanyaan' => 'Dimana lokasi kabupaten/kota tempat Anda bekerja?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "010100 - Kab. Kepulauan Seribu",
                "016000 - Kota Jakarta Pusat",
                "016100 - Kota Jakarta Utara",
                "016200 - Kota Jakarta Barat",
                "016300 - Kota Jakarta Selatan",
                "016400 - Kota Jakarta Timur",
                "020500 - Kab. Bogor",
                "020600 - Kab. Sukabumi",
                "020700 - Kab. Cianjur",
                "020800 - Kab. Bandung",
                "021000 - Kab. Sumedang",
                "021100 - Kab. Garut",
                "021200 - Kab. Tasikmalaya",
                "021400 - Kab. Ciamis",
                "021500 - Kab. Kuningan",
                "021600 - Kab. Majalengka",
                "021700 - Kab. Cirebon",
                "021800 - Kab. Indramayu",
                "021900 - Kab. Subang",
                "022000 - Kab. Purwakarta",
                "022100 - Kab. Karawang",
                "022200 - Kab. Bekasi",
                "022300 - Kab. Bandung Barat",
                "022500 - Kab. Pangandaran",
                "026000 - Kota Bandung",
                "026100 - Kota Bogor",
                "026200 - Kota Sukabumi",
                "026300 - Kota Cirebon",
                "026500 - Kota Bekasi",
                "026600 - Kota Depok",
                "026700 - Kota Cimahi",
                "026800 - Kota Tasikmalaya",
                "026900 - Kota Banjar",
                "030100 - Kab. Cilacap",
                "030200 - Kab. Banyumas",
                "030300 - Kab. Purbalingga",
                "030400 - Kab. Banjarnegara",
                "030500 - Kab. Kebumen",
                "030600 - Kab. Purworejo",
                "030700 - Kab. Wonosobo",
                "030800 - Kab. Magelang",
                "030900 - Kab. Boyolali",
                "031000 - Kab. Klaten",
                "031100 - Kab. Sukoharjo",
                "031200 - Kab. Wonogiri",
                "031300 - Kab. Karanganyar",
                "031400 - Kab. Sragen",
                "031500 - Kab. Grobogan",
                "031600 - Kab. Blora",
                "031700 - Kab. Rembang",
                "031800 - Kab. Pati",
                "031900 - Kab. Kudus",
                "032000 - Kab. Jepara",
                "032100 - Kab. Demak",
                "032200 - Kab. Semarang",
                "032300 - Kab. Temanggung",
                "032400 - Kab. Kendal",
                "032500 - Kab. Batang",
                "032600 - Kab. Pekalongan",
                "032700 - Kab. Pemalang",
                "032800 - Kab. Tegal",
                "032900 - Kab. Brebes",
                "036000 - Kota Magelang",
                "036100 - Kota Surakarta",
                "036200 - Kota Salatiga",
                "036300 - Kota Semarang",
                "036400 - Kota Pekalongan",
                "036500 - Kota Tegal",
                "040100 - Kab. Bantul",
                "040200 - Kab. Sleman",
                "040300 - Kab. Gunung Kidul",
                "040400 - Kab. Kulon Progo",
                "046000 - Kota Yogyakarta",
                "050100 - Kab. Gresik",
                "050200 - Kab. Sidoarjo",
                "050300 - Kab. Mojokerto",
                "050400 - Kab. Jombang",
                "050500 - Kab. Bojonegoro",
                "050600 - Kab. Tuban",
                "050700 - Kab. Lamongan",
                "050800 - Kab. Madiun",
                "050900 - Kab. Ngawi",
                "051000 - Kab. Magetan",
                "051100 - Kab. Ponorogo",
                "051200 - Kab. Pacitan",
                "051300 - Kab. Kediri",
                "051400 - Kab. Nganjuk",
                "051500 - Kab. Blitar",
                "051600 - Kab. Tulungagung",
                "051700 - Kab. Trenggalek",
                "051800 - Kab. Malang",
                "051900 - Kab. Pasuruan",
                "052000 - Kab. Probolinggo",
                "052100 - Kab. Lumajang",
                "052200 - Kab. Bondowoso",
                "052300 - Kab. Situbondo",
                "052400 - Kab. Jember",
                "052500 - Kab. Banyuwangi",
                "052600 - Kab. Pamekasan",
                "052700 - Kab. Sampang",
                "052800 - Kab. Sumenep",
                "052900 - Kab. Bangkalan",
                "056000 - Kota Surabaya",
                "056100 - Kota Malang",
                "056200 - Kota Madiun",
                "056300 - Kota Kediri",
                "056400 - Kota Mojokerto",
                "056500 - Kota Blitar",
                "056600 - Kota Pasuruan",
                "056700 - Kota Probolinggo",
                "056800 - Kota Batu",
                "060100 - Kab. Aceh Besar",
                "060200 - Kab. Pidie",
                "060300 - Kab. Aceh Utara",
                "060400 - Kab. Aceh Timur",
                "060500 - Kab. Aceh Tengah",
                "060600 - Kab. Aceh Barat",
                "060700 - Kab. Aceh Selatan",
                "060800 - Kab. Aceh Tenggara",
                "061100 - Kab. Simeulue",
                "061200 - Kab. Bireuen",
                "061300 - Kab. Aceh Singkil",
                "061400 - Kab. Aceh Tamiang",
                "061500 - Kab. Nagan Raya",
                "061600 - Kab. Aceh Jaya",
                "061700 - Kab. Aceh Barat Daya",
                "061800 - Kab. Gayo Lues",
                "061900 - Kab. Bener Meriah",
                "062000 - Kab. Pidie Jaya",
                "066000 - Kota Sabang",
                "066100 - Kota Banda Aceh",
                "066200 - Kota Lhokseumawe",
                "066300 - Kota Langsa",
                "066400 - Kab. Sabussalam",
                "070100 - Kab. Deli Serdang",
                "070200 - Kab. Langkat",
                "070300 - Kab. Karo",
                "070400 - Kab. Simalungun",
                "070500 - Kab. Dairi",
                "070600 - Kab. Asahan",
                "070700 - Kab. Labuhan Batu",
                "070800 - Kab. Tapanuli Utara",
                "070900 - Kab. Tapanuli Tengah",
                "071000 - Kab. Tapanuli Selatan",
                "071100 - Kab. Nias",
                "071500 - Kab. Mandailing Natal",
                "071600 - Kab. Toba Samosir",
                "071700 - Kab. Nias Selatan",
                "071800 - Kab. Pak pak Bharat",
                "071900 - Kab. Humbang Hasudutan",
                "072000 - Kab. Samosir",
                "072100 - Kab. Serdang Bedagai",
                "072200 - Kab. Batubara",
                "072300 - Kab. Padang Lawas utara",
                "072400 - Kab. Padang Lawas",
                "072500 - Kab. Labuhan Batu Utara",
                "072600 - Kab. Labuhan Batu Selatan",
                "072700 - Kab. Nias Barat",
                "072800 - Kab. Nias Utara",
                "076000 - Kota Medan",
                "076100 - Kota Binjai",
                "076200 - Kota Tebing Tinggi",
                "076300 - Kota Pematang Siantar",
                "076400 - Kota Tanjung Balai",
                "076500 - Kota Sibolga",
                "076600 - Kota Padang Sidempuan",
                "076700 - Kota Gunung Sitoli",
                "080100 - Kab. Agam",
                "080200 - Kab. Pasaman",
                "080300 - Kab. Lima Puluh Koto",
                "080400 - Kab. Solok",
                "080500 - Kab. Padang Pariaman",
                "080600 - Kab. Pesisir Selatan",
                "080700 - Kab. Tanah Datar",
                "080800 - Kab. Sawahlunto/ Sijunjung",
                "081000 - Kab. Kepulauan Mentawai",
                "081100 - Kab. Solok Selatan",
                "081200 - Kab. Dharmas Raya",
                "081300 - Kab. Pasaman Barat",
                "086000 - Kota Bukittinggi",
                "086100 - Kota Padang",
                "086200 - Kota Padang Panjang",
                "086300 - Kota Sawah Lunto",
                "086400 - Kota Solok",
                "086500 - Kota Payakumbuh",
                "086600 - Kota Pariaman",
                "090100 - Kab. Kampar",
                "090200 - Kab. Bengkalis",
                "090400 - Kab. Indragiri Hulu",
                "090500 - Kab. Indragiri Hilir",
                "090800 - Kab. Pelalawan",
                "090900 - Kab. Rokan Hilir",
                "091000 - Kab. Siak",
                "091100 - Kab. Kuantan Singingi",
                "091400 - Kab. Rokan Hulu",
                "091500 - Kab. Kepulauan Meranti",
                "096000 - Kota Pekanbaru",
                "096200 - Kota Dumai",
                "100100 - Kab. Batang Hari",
                "100200 - Kab. Bungo",
                "100300 - Kab. Sarolangun",
                "100400 - Kab. Tanjung Jabung Barat",
                "100500 - Kab. Kerinci",
                "100600 - Kab. Tebo",
                "100700 - Kab. Muaro Jambi",
                "100800 - Kab. Tanjung Jabung Timur",
                "100900 - Kab. Merangin",
                "106000 - Kota Jambi",
                "106100 - Kab. Sungai Penuh",
                "110100 - Kab. Musi Banyu Asin",
                "110200 - Kab. Ogan Komering Ilir",
                "110300 - Kab. Ogan Komering Ulu",
                "110400 - Kab. Muara Enim",
                "110500 - Kab. Lahat",
                "110600 - Kab. Musi Rawas",
                "110700 - Kab. Banyuasin",
                "110800 - Kab. Ogan Komering Ulu Timur",
                "110900 - Kab. Ogan Komering Ulu Selatan",
                "111000 - Kab. Ogan Ilir",
                "111100 - Kab. Empat Lawang",
                "111200 - Kab. Penukal Abab Lematang Ilir",
                "111300 - Kab. Musi Rawas Utara",
                "116000 - Kota Palembang",
                "116100 - Kota Prabumulih",
                "116200 - Kota Lubuk Linggau",
                "116300 - Kota Pagar Alam",
                "120100 - Kab. Lampung Selatan",
                "120200 - Kab. Lampung Tengah",
                "120300 - Kab. Lampung Utara",
                "120400 - Kab. Lampung Barat",
                "120500 - Kab. Tulang Bawang",
                "120600 - Kab. Tenggamus",
                "120700 - Kab. Lampung Timur",
                "120800 - Kab. Way Kanan",
                "120900 - Kab. Pasawaran",
                "121000 - Kab. Tulang Bawang Barat",
                "121100 - Kab. Mesuji",
                "121200 - Kab. Pringsewu",
                "121300 - Kab. Pesisir Barat",
                "126000 - Kota Bandar Lampung",
                "126100 - Kota Metro",
                "130100 - Kab. Sambas",
                "130200 - Kab. Pontianak",
                "130300 - Kab. Sanggau",
                "130400 - Kab. Sintang",
                "130500 - Kab. Kapuas Hulu",
                "130600 - Kab. Ketapang",
                "130800 - Kab. Bengkayang",
                "130900 - Kab. Landak",
                "131000 - Kab. Sekadau",
                "131100 - Kab. Melawi",
                "131200 - Kab. Kayong Utara",
                "131300 - Kab. Kuburaya",
                "136000 - Kota Pontianak",
                "136100 - Kota Singkawang",
                "140100 - Kab. Kapuas",
                "140200 - Kab. Barito Selatan",
                "140300 - Kab. Barito Utara",
                "140400 - Kab. Kotawaringin Timur",
                "140500 - Kab. Kotawaringin Barat",
                "140600 - Kab. Katingan",
                "140700 - Kab. Seruyan",
                "140800 - Kab. Sukamara",
                "140900 - Kab. Lamandau",
                "141000 - Kab. Gunung Mas",
                "141100 - Kab. Pulang Pisau",
                "141200 - Kab. Murung Raya",
                "141300 - Kab. Barito Timur",
                "146000 - Kota Palangka Raya",
                "150100 - Kab. Banjar",
                "150200 - Kab. Tanah Laut",
                "150300 - Kab. BaritoKuala",
                "150400 - Kab. Tapin",
                "150500 - Kab. Hulu Sungai Selatan",
                "150600 - Kab. Hulu Sungai Tengah",
                "150700 - Kab. Hulu Sungai Utara",
                "150800 - Kab. Tabalong",
                "150900 - Kab. Kota Baru",
                "151000 - Kab. Balangan",
                "151100 - Kab. Tanah Bumbu",
                "156000 - Kota Banjarmasin",
                "156100 - Kota Banjarbaru",
                "160100 - Kab. Pasir",
                "160200 - Kab. Kutai Kartanegara",
                "160300 - Kab. Berau",
                "160400 - Kab. Bulongan",
                "160700 - Kab. Malinau",
                "160800 - Kab. Nunukan",
                "160900 - Kab. Kutai Barat",
                "161000 - Kab. Kutai Timur",
                "161100 - Kab. Penajam Paser Utara",
                "161200 - Kab. Mahakam Ulu",
                "165400 - Kab. Tanah Tidung",
                "166000 - Kota Samarinda",
                "166100 - Kota Balikpapan",
                "166200 - Kota Tarakan",
                "166300 - Kota Bontang",
                "170100 - Kab. Bolaang Mongondaw",
                "170200 - Kab. Minahasa",
                "170300 - Kab. Kep. Sangihe",
                "170400 - Kab. Kepulauan Talaud",
                "170500 - Kab. Minahasa Selatan",
                "170600 - Kab. Minahasa Utara",
                "170800 - Kab. Bolaang Mongondow Utara",
                "170900 - Kab. Kepulauan Sitaro",
                "171000 - Kab. Minahasa Tenggara",
                "171100 - Kab. Bolaang Mongondow Timur",
                "171200 - Kab. Bolaang Mongondow Selatan",
                "176000 - Kota Manado",
                "176100 - Kota Bitung",
                "176200 - Kota Tomohon",
                "176300 - Kota. Kotamobagu",
                "180100 - Kab. Banggai Kepulauan",
                "180200 - Kab. Donggala",
                "180300 - Kab. Parigi Mautong",
                "180400 - Kab. Banggai",
                "180500 - Kab. Buol",
                "180600 - Kab. Toli-Toli",
                "180700 - Kab. Marowali",
                "180800 - Kab. Poso",
                "180900 - Kab. Tojo Una-Una",
                "181000 - Kab. Sigi",
                "181100 - Kab. Banggai Laut",
                "181200 - Kab. Morowali Utara",
                "186000 - Kota Palu",
                "190100 - Kab. Maros",
                "190200 - Kab. Pangkajene Kepulauan",
                "190300 - Kab. Gowa",
                "190400 - Kab. Takalar",
                "190500 - Kab. Jeneponto",
                "190600 - Kab. Barru",
                "190700 - Kab. Bone",
                "190800 - Kab. Wajo",
                "190900 - Kab. Soppeng",
                "191000 - Kab. Bantaeng",
                "191100 - Kab. Bulukumba",
                "191200 - Kab. Sinjai",
                "191300 - Kab. Selayar",
                "191400 - Kab. Pinrang",
                "191500 - Kab. Sidenreng Rappang",
                "191600 - Kab. Enrekang",
                "191700 - Kab. Luwu",
                "191800 - Kab. Tana Toraja",
                "192400 - Kab. Luwu Utara",
                "192600 - Kab. Luwu Timur",
                "192700 - Kab. Toraja Utara",
                "196000 - Kota Makassar",
                "196100 - Kota Pare-Pare",
                "196200 - Kota Palopo",
                "200100 - Kab. Konawe",
                "200200 - Kab. Muna",
                "200300 - Kab. Buton",
                "200400 - Kab. Kolaka",
                "200500 - Kab. Konawe Selatan",
                "200600 - Kab. Wakatobi",
                "200700 - Kab. Bombana",
                "200800 - Kab. Kolaka Utara",
                "200900 - Kab. Konawe Utara",
                "201000 - Kab. Buton Utara",
                "201100 - Kab. Kolaka Timur",
                "201200 - Kab. Konawe Kepulauan",
                "201300 - Kab. Muna Barat",
                "201400 - Kab. Buton Selatan",
                "201600 - Kab. Buton Tengah",
                "206000 - Kota Kupang",
                "210100 - Kab. Maluku Tengah",
                "210200 - Kab. Maluku Tenggara",
                "210300 - Kab. Buru",
                "210400 - Kab. Maluku Tenggara Barat",
                "210500 - Kab. Seram Bagian Barat",
                "210600 - Kab. Seram Bagian Timur",
                "210700 - Kab. Kepulauan Aru",
                "210800 - Kab. Maluku Barat Daya",
                "210900 - Kab. Buru Selatan",
                "216000 - Kota Ambon",
                "216100 - Kota. Tual",
                "220100 - Kab. Buleleng",
                "220200 - Kab. Jembrana",
                "220300 - Kab. Tabanan",
                "220400 - Kab. Badung",
                "220500 - Kab. Gianyar",
                "220600 - Kab. Klungkung",
                "220700 - Kab. Bangli",
                "220800 - Kab. Karang Asem",
                "226000 - Kota Denpasar",
                "230100 - Kab. Lombok Barat",
                "230200 - Kab. Lombok Tengah",
                "230300 - Kab. Lombok Timur",
                "230400 - Kab. Sumbawa",
                "230500 - Kab. Dompu",
                "230600 - Kab. Bima",
                "230700 - Kab. Sumbawa Barat",
                "230800 - Kab. Lombok Utara",
                "236000 - Kota Mataram",
                "236100 - Kota Bima",
                "240100 - Kab. Kupang",
                "240300 - Kab. Timor Tengah Selatan",
                "240400 - Kab. Timor Tengah Utara",
                "240500 - Kab. Belu",
                "240600 - Kab. Alor",
                "240700 - Kab. Flores Timur",
                "240800 - Kab. Sikka",
                "240900 - Kab. Ende",
                "241000 - Kab. Ngada",
                "241100 - Kab. Manggarai",
                "241200 - Kab. Sumba Timur",
                "241300 - Kab. Sumba Barat",
                "241400 - Kab. Lembata",
                "241500 - Kab. Rote-Ndao",
                "241600 - Kab. Manggarai Barat",
                "241700 - Kab. Nagakeo",
                "241800 - Kab. Sumba Tengah",
                "241900 - Kab. Sumba Barat Daya",
                "242000 - Kab. Manggarai Timur",
                "242100 - Kab. Sabu Raijua",
                "242200 - Kab. Malaka",
                "246000 - Kota Kupang",
                "250100 - Kab. Jayapura",
                "250200 - Kab. Biak Numfor",
                "250300 - Kab. Yapen Waropen",
                "250700 - Kab. Merauke",
                "250800 - Kab. Jayawijaya",
                "250900 - Kab. Nabire",
                "251000 - Kab. Paniai",
                "251100 - Kab. Puncak Jaya",
                "251200 - Kab. Mimika",
                "251300 - Kab. Boven Digoel",
                "251400 - Kab. Mappi",
                "251500 - Kab. Asmat",
                "251600 - Kab. Yahukimo",
                "251700 - Kab. Pegunungan Bintang",
                "251800 - Kab. Tolikara",
                "251900 - Kab. Sarmi",
                "252000 - Kab. Keerom",
                "252600 - Kab. Waropen",
                "252700 - Kab. Supiori",
                "252800 - Kab. Memberamo Raya",
                "252900 - Kab. Nduga",
                "253000 - Kab. Lanny Jaya",
                "253100 - Kab. Membramo Tengah",
                "253200 - Kab. Yalimo",
                "253300 - kab. Puncak",
                "253400 - Kab. Dogiyai",
                "253500 - Kab. Deiyai",
                "253600 - Kab. Intan Jaya",
                "256000 - Kota Jayapura",
                "260100 - Kab. Bengkulu Utara",
                "260200 - Kab. Rejang Lebong",
                "260300 - Kab. Bengkulu Selatan",
                "260400 - Kab. Muko-muko",
                "260500 - Kab. Kepahiang",
                "260600 - Kab. Lebong",
                "260700 - Kab. Kaur",
                "260800 - Kab. Seluma",
                "260900 - Kab. Bengkulu Tengah",
                "266000 - Kota Bengkulu",
                "270100 - Kab. Pulau Taliabu",
                "270200 - Kab. Halmahera Tengah",
                "270300 - Kab. Halmahera Barat",
                "270400 - Kab. halmahera Utara",
                "270500 - Kab. Halmahera Selatan",
                "270600 - Kab. Halmahera Timur",
                "270700 - Kab. Kepulauan Sula",
                "270800 - Kab. Kepulauan Morotai",
                "276000 - Kota Ternate",
                "276100 - Kota Tidore Kepulauan",
                "300100 - Kab. Boalemo",
                "300200 - Kab. Gorontalo",
                "300300 - Kab. Pohuwato",
                "300400 - Kab. Bone Bolango",
                "300500 - Kab. Gorontalo Utara",
                "306000 - Kota Gorontalo",
                "310100 - Kab. Bintan",
                "310200 - Kab. Karimun",
                "310300 - Kab. Natuna",
                "310400 - Kab. Lingga",
                "310500 - Kab. Kepulauan Anambas",
                "316000 - Kota Batam",
                "316100 - Kota Tanjungpinang",
                "320100 - Kab. Fak-Fak",
                "320200 - Kab. Kaimana",
                "320300 - Kab. Teluk Wondama",
                "320400 - Kab. Teluk Bintuni",
                "320500 - Kab. Manokwari",
                "320600 - Kab. Sorong Selatan",
                "320700 - Kab. Sorong",
                "320800 - Kab.Raja Ampat",
                "320900 - Kab. Tambrauw",
                "321000 - Kab. Maybrat",
                "321100 - Kab. Pegunungan Arfak",
                "321200 - Kab. Manokwari Selatan",
                "326000 - Kota Sorong",
                "330100 - Kab. Mamuju",
                "330200 - Kab. Mamuju Utara",
                "330300 - Kab. Polewali Mamasa",
                "330400 - Kab. Mamasa",
                "330500 - Kab. Majene",
                "330600 - Kab. Mamuju Tengah",
                "340100 - Kab. Malinau",
                "340200 - Kab. Bulungan",
                "340300 - Kab. Tana Tidung",
                "340500 - Kab. Nunukan",
                "346000 - Kota Tarakan",
                "999999 - Luar Negeri"
            ]),
            'index' => 16,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1101',
            'pertanyaan' => 'Apa jenis perusahaan/instansi/institusi tempat anda bekerja sekarang?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Instansi pemerintah",
                "2 - Organisasi non-profit/Lembaga Swadaya Masyarakat",
                "3 - Perusahaan swasta",
                "4 - Wiraswasta/perusahaan sendiri",
                "6 - BUMN/BUMD",
                "7 - Institusi/Organisasi Multilateral",
                "5 - Lainnya",
            ]),
            'index' => 17,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f5b',
            'pertanyaan' => 'Apa nama perusahaan/kantor tempat Anda bekerja?',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 18,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f5c',
            'pertanyaan' => 'Bila Anda berwiraswasta, apa posisi/jabatan Anda saat ini ?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Founder",
                "2 - Co-Founder",
                "3 - Staff",
                "4 - Frelance Kerja Lepas",
            ]),
            'index' => 19,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f5d',
            'pertanyaan' => 'Apa tingkatan tempat kerja Anda?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Lokal/wilayah/wiraswasta tidak berbadan hukum",
                "2 - Nasional/wiraswasta berbadan hukum",
                "3 - Multinasional/Internasional",
            ]),
            'index' => 21,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f18a',
            'pertanyaan' => 'Sumber biaya Studi Lanjut Anda?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "Biaya Sendiri",
                "Bea Siswa",
            ]),
            'index' => 22,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f18b',
            'pertanyaan' => 'Nama Perguruan Tinggi Studi Lanjut Anda?',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 23,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f18c',
            'pertanyaan' => 'Nama Program Studi Studi Lanjut Anda?',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 24,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f18d',
            'pertanyaan' => 'Tanggal Masuk Awal Studi Lanjut Anda?',
            'tipe_id' => 6,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 25,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1201',
            'pertanyaan' => 'Sebutkan sumberdana dalam pembiayaan kuliah? (bukan ketika Studi Lanjut)',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Biaya Sendiri/Keluarga",
                "2 - Beasiswa ADIK",
                "3 - Beasiswa BIDIKMISI",
                "4 - Beasiswa PPA",
                "5 - Beasiswa AFIRMASI",
                "6 - Beasiswa Perusahaan/Swasta",
                "7 - Lainnya",
            ]),
            'index' => 26,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f14',
            'pertanyaan' => 'Seberapa erat hubungan bidang studi dengan pekerjaan Anda?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangar Erat",
                "2 - Erat",
                "3 - Cukup Erat",
                "4 - Kurang Erat",
                "5 - Tidak sama sekali",
            ]),
            'index' => 27,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f15',
            'pertanyaan' => 'Tingkat pendidikan apa yang paling tepat/sesuai untuk pekerjaan anda saat ini?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Setingkat lebih tinggi",
                "2 - Tingkat yang sama",
                "3 - Setingkat lebih rendah",
                "4 - Tidak perlu pendidikan tinggi",
            ]),
            'index' => 28,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1761',
            'pertanyaan' => 'Pada tingkat mana kompetensi ETIKA anda pada SAAT LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 29,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1762',
            'pertanyaan' => 'Pada tingkat mana kompetensi ETIKA anda pada SAAT INI?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 30,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1763',
            'pertanyaan' => 'Pada tingkat mana kompetensi KEAHLIAN BERDASARKAN BIDANG ILMU anda kuasai pada SAAT LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 31,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1764',
            'pertanyaan' => 'Pada tingkat mana kompetensi KEAHLIAN BERDASARKAN BIDANG ILMU anda kuasai pada SAAT INI?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 32,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1765',
            'pertanyaan' => 'Pada tingkat mana kompetensi BAHASA INGGRIS anda kuasai pada SAAT LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 33,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1766',
            'pertanyaan' => 'Pada tingkat mana kompetensi BAHASA INGGRIS anda kuasai pada SAAT INI?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 34,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1767',
            'pertanyaan' => 'Pada tingkat mana kompetensi TEKNOLOGI INFORMASI anda kuasai pada SAAT LULUS? ',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 35,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1768',
            'pertanyaan' => 'Pada tingkat mana kompetensi TEKNOLOGI INFORMASI anda kuasai pada SAAT INI?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 36,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1769',
            'pertanyaan' => 'Pada tingkat mana kompetensi KOMUNIKASI anda kuasai pada SAAT LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 37,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1770',
            'pertanyaan' => 'Pada tingkat mana kompetensi KOMUNIKASI anda kuasai pada SAAT INI?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 38,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1771',
            'pertanyaan' => 'Pada tingkat mana kompetensi KERJA SAMA TIM anda pada SAAT LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 39,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1772',
            'pertanyaan' => 'Pada tingkat mana kompetensi KERJA SAMA TIM anda pada SAAT INI?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 40,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1773',
            'pertanyaan' => 'Pada tingkat mana kompetensi PENGEMBANGAN DIRI anda pada SAAT LULUS?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 41,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1774',
            'pertanyaan' => 'Pada tingkat mana kompetensi PENGEMBANGAN DIRI anda pada SAAT INI?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Rendah",
                "2 - Rendah",
                "3 - Netral",
                "4 - Tinggi",
                "5 - Sangat Tinggi",
            ]),
            'index' => 42,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f21',
            'pertanyaan' => 'Perkuliahan',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Besar",
                "2 - Besar",
                "3 - Cukup Besar",
                "4 - Kurang",
                "5 - Tidak Sama Sekali",
            ]),
            'index' => 43,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f22',
            'pertanyaan' => 'Demonstrasi',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Besar",
                "2 - Besar",
                "3 - Cukup Besar",
                "4 - Kurang",
                "5 - Tidak Sama Sekali",
            ]),
            'index' => 44,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f23',
            'pertanyaan' => 'Partisipasi dalam proyek riset',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Besar",
                "2 - Besar",
                "3 - Cukup Besar",
                "4 - Kurang",
                "5 - Tidak Sama Sekali",
            ]),
            'index' => 45,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f24',
            'pertanyaan' => 'Magang',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Besar",
                "2 - Besar",
                "3 - Cukup Besar",
                "4 - Kurang",
                "5 - Tidak Sama Sekali",
            ]),
            'index' => 46,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f25',
            'pertanyaan' => 'Praktikum',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Besar",
                "2 - Besar",
                "3 - Cukup Besar",
                "4 - Kurang",
                "5 - Tidak Sama Sekali",
            ]),
            'index' => 47,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f26',
            'pertanyaan' => 'Kerja Lapangan',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Besar",
                "2 - Besar",
                "3 - Cukup Besar",
                "4 - Kurang",
                "5 - Tidak Sama Sekali",
            ]),
            'index' => 48,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f27',
            'pertanyaan' => 'Diskusi',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Sangat Besar",
                "2 - Besar",
                "3 - Cukup Besar",
                "4 - Kurang",
                "5 - Tidak Sama Sekali",
            ]),
            'index' => 49,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f301',
            'pertanyaan' => 'Kapan anda mulai mencari pekerjaan?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Saya mencari kerja sebelum lulus",
                "2 - Saya mencari kerja sesudah wisuda",
                "3 - Saya tidak mencari kerja",
            ]),
            'index' => 50,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f302',
            'pertanyaan' => 'Saya mencari pekerjaan, Kira-kira ....... bulan SEBELUM lulus',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'index' => 51,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f303',
            'pertanyaan' => 'Saya mencari pekerjaan, Kira-kira ....... bulan SETELAH wisuda',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'index' => 52,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f401',
            'pertanyaan' => 'Melalui iklan di koran/majalah, brosur ?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 53,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f402',
            'pertanyaan' => 'Melamar ke perusahaan tanpa mengetahui lowongan yang ada?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 54,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f403',
            'pertanyaan' => 'Pergi ke bursa/pameran kerja',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 55,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f404',
            'pertanyaan' => 'Mencari lewat internet/iklan online/milis',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 56,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f405',
            'pertanyaan' => 'Dihubungi oleh perusahaan',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 57,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f406',
            'pertanyaan' => 'Menghubungi Kemenakertrans',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 58,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f407',
            'pertanyaan' => 'Menghubungi agen tenaga kerja komersial/swasta',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 59,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f408',
            'pertanyaan' => 'Memperoleh informasi dari pusat/kantor pengembangan karir fakultas/universitas',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 60,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f409',
            'pertanyaan' => 'Menghubungi kantor kemahasiswaan/hubungan alumni',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 61,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f410',
            'pertanyaan' => 'Membangun jejaring (network) sejak masih kuliah',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 62,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f411',
            'pertanyaan' => 'Melalui relasi (misalnya dosen, orang tua, saudara, teman, Ikatan Alumni dll.)',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 63,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f412',
            'pertanyaan' => 'Membangun bisnis sendiri)',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 64,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f413',
            'pertanyaan' => 'Melalui penempatan kerja atau magang',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 65,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f414',
            'pertanyaan' => 'Bekerja di tempat yang sama dengan tempat kerja semasa kuliah',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 66,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f415',
            'pertanyaan' => 'Lainnya',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak",
                "1 - Iya",
            ]),
            'index' => 67,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f7a',
            'pertanyaan' => 'Berapa banyak perusahaan/instansi/institusi yang mengundang anda untuk wawancara?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
            'index' => 68,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1001',
            'pertanyaan' => 'Apakah Anda aktif mencari pekerjaan dalam 4 minggu terakhir? Pilihlah satu jawaban',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "1 - Tidak",
                "2 - Tidak, tapi saya sedang menunggu hasil lamaran kerja",
                "3 - Ya, saya akan mulai bekerja dalam 2 minggu ke depan",
                "4 - Ya, tapi saya belum pasti akan bekerja dalam 2 minggu ke depan",
                "5 - Lainnya",
            ]),
            'index' => 69,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1601',
            'pertanyaan' => 'Apakah pekerjaan anda saat ini tidak sesuai dengan pendidikan anda ?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Tidak sesuai",
                "1 - Pekerjaan saya sekarang sudah sesuai dengan pendidikan saya",
            ]),
            'index' => 70,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1602',
            'pertanyaan' => 'Apakah pekerjaan anda saat ini tidak sesuai dengan pendidikan anda ?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Saya belum mendapatkan pekerjaan yang lebih sesuai",
            ]),
            'index' => 71,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1603',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Di pekerjaan ini saya memeroleh prospek karir yang baik",
            ]),
            'index' => 72,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1604',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Saya lebih suka bekerja di area pekerjaan yang tidak ada hubungannya dengan pendidikan saya",
            ]),
            'index' => 73,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1605',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Saya dipromosikan ke posisi yang kurang berhubungan dengan pendidikan saya dibanding posisi sebelumnya",
            ]),
            'index' => 74,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1606',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Saya dapat memeroleh pendapatan yang lebih tinggi di pekerjaan ini",
            ]),
            'index' => 75,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1607',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Pekerjaan saya saat ini lebih aman/terjamin/secure",
            ]),
            'index' => 76,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1608',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Pekerjaan saya saat ini lebih menarik",
            ]),
            'index' => 77,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1609',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Pekerjaan saya saat ini lebih memungkinkan saya mengambil pekerjaan tambahan/jadwal yang fleksibel, dll",
            ]),
            'index' => 78,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1610',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Pekerjaan saya saat ini lokasinya lebih dekat dari rumah saya",
            ]),
            'index' => 79,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1611',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Pekerjaan saya saat ini dapat lebih menjamin kebutuhan keluarga saya",
            ]),
            'index' => 80,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1612',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya?',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Pada awal meniti karir ini, saya harus menerima pekerjaan yang tidak berhubungan dengan pendidikan saya",
            ]),
            'index' => 81,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1613',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya? Selain pilihan dijawaban soal diatas',
            'tipe_id' => 8,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'options' => json_encode([
                "0 - Pekerjaan saya sudah sesuai",
                "1 - Lainnya",
            ]),
            'index' => 82,
        ]);
        PaketQuesionerDetail::create([
            'kode_pertanyaan' => 'f1614',
            'pertanyaan' => 'Jika pekerjaan anda saat ini tidak sesuai dengan pendidikan anda, mengapa anda mengambilnya? Selain pilihan dijawaban soal diatas, Tuliskan',
            'tipe_id' => 1,
            'id_paket_quesioners' => 2,
            'is_required' => 1,
            'index' => 83,
        ]);
    }
}
